# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-05 05:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('okta_user_id', models.CharField(max_length=100)),
                ('calendar_id', models.CharField(max_length=100)),
                ('event_uid', models.CharField(max_length=100)),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
                ('description', models.TextField(blank=True)),
                ('summary', models.CharField(max_length=255)),
                ('subject', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=100)),
                ('dueDate', models.DateField()),
                ('timeSpent', models.IntegerField()),
            ],
        ),
    ]
