# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-17 02:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_event_app', '0002_auto_20161007_2036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='event_uid',
            field=models.CharField(db_index=True, max_length=100, unique=True),
        ),
    ]
