# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-25 22:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_event_app', '0003_auto_20161017_0218'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='dueDate',
            new_name='due_date',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='timeSpent',
            new_name='time_spent',
        ),
    ]
