# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-26 00:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_event_app', '0004_auto_20161025_2222'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='status_code',
            field=models.CharField(default='N', max_length=2),
            preserve_default=False,
        ),
    ]
