# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-09 07:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_event_app', '0005_task_status_code'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='task',
            table='task',
        ),
    ]
