# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-09 07:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_event_app', '0006_auto_20161209_0725'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPreference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('okta_user_id', models.CharField(db_index=True, max_length=100, unique=True)),
                ('time_zone', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'user_preference',
            },
        ),
    ]
