# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-09 07:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_event_app', '0007_userpreference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpreference',
            name='time_zone',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
