# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-13 18:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_event_app', '0008_auto_20161209_0732'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='attendees',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='task',
            name='organizer',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
