# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-01-20 23:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_event_app', '0012_auto_20161213_1850'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='opportunity',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
