# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-01-24 00:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_event_app', '0013_task_opportunity'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='completed_time',
            field=models.CharField(blank=True, max_length=17),
        ),
    ]
